name: Deploy and Send Secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Enviar secrets para o servidor
      - name: Send Secrets to Server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          AUTH_URL: ${{ secrets.AUTH_URL }}
          EXTERNAL_SERVICE_URL: ${{ secrets.EXTERNAL_SERVICE_URL }}
        run: |
          curl -X POST http://localhost:1234/store-secrets \
          -H "Content-Type: application/json" \
          -d "{\"database_url\":\"$DATABASE_URL\", \"api_base_url\":\"$API_BASE_URL\", \"auth_url\":\"$AUTH_URL\", \"external_service_url\":\"$EXTERNAL_SERVICE_URL\"}"

      # Iniciar o servidor (Exemplo: No caso de estar usando PM2 ou outro processo gerenciado)
      - name: Start Server
        env:
          PORT: 1234
        run: |
          npm install
          npm run build
          npm start
